api_platform:
    title: 'Telefony Ldap SRV'
    version: '1.0.0'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    exception_to_status:
        Adldap\Auth\BindException: 400
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header
