#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#

# api_users_register:
#     path: /api/users
#     methods: [POST]
#     defaults:
#         _controller: App\Controller\RegisterUserController::class
#         _api_resource_class: App\Entity\User
#         _api_item_operation_name: registerUsers

api_login:
    path:     /api/login
    methods:  [POST]
