resources:
  App\Entity\Domain:
    attributes:
      access_control: is_granted('ROLE_ADMIN')
      access_control_message: "You need to be an administrator to do this."
    itemOperations:
      get:
        method: 'GET'
      put:
        method: 'PUT'
      delete:
        method: 'DELETE'
      LdapGetData:
        method: 'POST'
        path: '/ldap_fetch/{id}'
        controller: App\Controller\LdapFetchController
        input: App\Dto\LdapFetchInput
        output: false
        swagger_context:
          summary: 'Creates LdapUsers and LdapPhoneNumbers.'
          parameters:
            - in: path
              name: id
              required: true
              type: integer
              description: 'ID of Domain which will be used to fetch the data by.'
            - in: body
              name: credentials
              required: true
              schema:
                type: object
                properties:
                  login:
                    type: string
                    example: my_username
                  password:
                    type: string
                    example: my_password
                  query:
                    type: string
                    example: allUsers
                    default: 'allUsers'
          responses:
            200:
              description: "The count of changes will be in the response."
            400:
              description: "There was an error while procesing the request, the reason is in the response."
