resources:
  App\Entity\LdapUser:
    collectionOperations:
      get:
        method: 'GET'
        formats:
          0: 'json'
          vcard: 'text/x-vcard'
          1: 'jsonld'
          csv: 'text/csv'
          YealinkIPPhoneBook: application/vnd.xml.yealink
    itemOperations:
      get:
        method: 'GET'
        formats:
          0: 'json'
          vcard: 'text/x-vcard'
          1: 'jsonld'
          csv: 'text/csv'
    attributes:
      normalization_context:
        groups: ["read_ldap_user"]
      pagination_enabled: false
    properties:
      ldapPhoneNumbers:
          subresource:
              resourceClass: 'App\Entity\LdapPhoneNumbers'
              collection: true
