resources:
  App\Entity\LdapPhoneNumbers:
    collectionOperations:
      get:
        method: 'GET'
    itemOperations:
      get:
        method: 'GET'
    attributes:
      pagination_enabled: false
      normalization_context:
        groups: ["read_phone_numbers"]
