resources:
  App\Entity\LdapUser:
    collectionOperations:
      get:
        method: 'GET'
    itemOperations:
      get:
        method: 'GET'
    attributes:
      formats:
        0: 'json'
        vcard: 'text/x-vcard'
        1: 'jsonld'
        csv: 'text/csv'
        YealinkIPPhoneBook: application/vnd.xml.yealink
      normalization_context:
        groups: ["read_ldap_user"]
      pagination_enabled: false
    properties:
      phoneNumbers:
          subresource:
              resourceClass: 'App\Entity\PhoneNumbers'
              collection: true
